export const OCCUPATIONS = [
	"Academic researcher",
	"Accountant",
	"Architect",
	"Artist",
	"Backend developer",
	"Business analyst",
	"Chef",
	"Civil engineer",
	"Community manager",
	"Consultant",
	"Content designer",
	"Customer support",
	"Data analyst",
	"Data scientist",
	"Designer",
	"DevOps engineer",
	"Doctor",
	"Educator",
	"Electrical engineer",
	"Engineering manager",
	"Farmer",
	"Founder",
	"Frontend developer",
	"Full-stack developer",
	"Game developer",
	"Graphic designer",
	"Human resources",
	"Intern",
	"Journalist",
	"Lawyer",
	"Lecturer",
	"Marketing specialist",
	"Mechanical engineer",
	"Mobile developer",
	"Nurse",
	"Product designer",
	"Product manager",
	"Project manager",
	"Public servant",
	"QA engineer",
	"Researcher",
	"Retail worker",
	"Retired",
	"Sales",
	"Scientist",
	"Security engineer",
	"Software engineer",
	"Student",
	"Systems administrator",
	"Teacher",
	"Technical writer",
	"UX researcher",
	"UX/UI designer",
	"Unemployed",
	"Other",
] as const;
